#!/bin/bash
#=============================================
# Author: Ajaogu Chiwendu Tessy
# Program: WinMingle Community C Training
# Description: Generating an assembly code (intel syntax)
#===============================================

gcc -S -masm=intel $CFILE -o ${CFILE/'.c'/'.s'}

