#!/bin/bash
#===========================================
# Author: Ajaogu Chiwendu Tessy
# Program: WinMingle Community C Training
# Description: Writing a script that compiles a C file and creates an executable named cisfun.
#==============================================

gcc -o cisfun $CFILE
 
